{"id":64,"name":"Object-Oriented Development",
"account_id":1,"uuid":"w4ycqEzxzwd3z9mgiuGPG8m776G94WUnhMzJRIgA","start_at":null,
"conclude_at":null,"grading_standard_id":null,"is_public":null,
"created_at":"2024-08-28T03:20:29Z","allow_student_forum_attachments":true,
"course_code":"A12","default_view":"modules","root_account_id":1,"enrollment_term_id":1,
"open_enrollment":null,"allow_wiki_comments":null,"self_enrollment":null,"license":null,
"restrict_enrollments_to_course_dates":false,"grade_passback_setting":null,"end_at":null,
"public_syllabus":false,"public_syllabus_to_auth":false,"storage_quota_mb":500,"is_public_to_auth_users":false,
"homeroom_course":false,"course_color":null,"friendly_name":null,"hide_final_grades":false,
"apply_assignment_group_weights":false,
"calendar":{"ics":"https://170.64.229.73/feeds/calendars/course_w4ycqEzxzwd3z9mgiuGPG8m776G94WUnhMzJRIgA.ics"},
"time_zone":"America/Denver","blueprint":false,"sis_course_id":"9","sis_import_id":null,"integration_id":null,"workflow_state":"unpublished"}
