#deployment properties
#Fri Dec 05 09:07:49 UTC 2025
mule.application.deployment.lazyInit.enableXmlValidations=true
mule.application.deployment.lazyInit=true
mule.application.deployment.addArtifactAstToRegistry=true
mule.application.deployment.addToolingObjectsToRegistry=true
mule.application.deployment.lazyConnections=true
