[
    {
        "id": "51",
        "body": "user: 42, quiz: 11, score: 10.0, time: 2024-08-22 08:16:40 +0000",
        "url": null,
        "grade": "10",
        "score": "10.0",
        "submitted_at": "2024-08-22T08:16:40Z",
        "assignment_id": "14",
        "user_id": "42",
        "submission_type": "online_quiz",
        "workflow_state": "graded",
        "grade_matches_current_submission": "true",
        "graded_at": "2024-08-22T08:16:40Z",
        "grader_id": "-11",
        "attempt": "1",
        "cached_due_date": null,
        "excused": null,
        "late_policy_status": null,
        "points_deducted": null,
        "grading_period_id": null,
        "extra_attempts": null,
        "posted_at": "2024-08-22T08:16:40Z",
        "redo_request": false,
        "custom_grade_status_id": null,
        "sticker": null,
        "late": false,
        "missing": false,
        "seconds_late": "0",
        "entered_grade": "10",
        "entered_score": "10.0",
        "preview_url": "https://170.64.229.73/courses/49/assignments/14/submissions/42?preview=1&version=1",
        "grader": "Graded on submission",
        "assignment_name": "CS Mod 1 Quiz",
        "user_name": "Bejoy Thomas",
        "current_grade": "10",
        "current_graded_at": "2024-08-22T08:16:40Z",
        "current_grader": "Graded on submission"
    },
    {
        "id": "47",
        "body": "user: 40, quiz: 11, score: 10.0, time: 2024-08-22 07:30:38 +0000",
        "url": null,
        "grade": "10",
        "score": "10.0",
        "submitted_at": "2024-08-22T07:30:38Z",
        "assignment_id": "14",
        "user_id": "40",
        "submission_type": "online_quiz",
        "workflow_state": "graded",
        "grade_matches_current_submission": "true",
        "graded_at": "2024-08-22T07:30:38Z",
        "grader_id": "-11",
        "attempt": "1",
        "cached_due_date": null,
        "excused": null,
        "late_policy_status": null,
        "points_deducted": null,
        "grading_period_id": null,
        "extra_attempts": null,
        "posted_at": "2024-08-22T07:30:38Z",
        "redo_request": "false",
        "custom_grade_status_id": null,
        "sticker": null,
        "late": "false",
        "missing": "false",
        "seconds_late": "0",
        "entered_grade": "10",
        "entered_score": "10.0",
        "preview_url": "https://170.64.229.73/courses/49/assignments/14/submissions/40?preview=1&version=1",
        "grader": "Graded on submission",
        "assignment_name": "CS Mod 1 Quiz",
        "user_name": "Virat Kholi",
        "current_grade": "10",
        "current_graded_at": "2024-08-22T07:30:38Z",
        "current_grader": "Graded on submission"
    },
    {
        "id": "49",
        "body": "user: 1, quiz: 11, score: 10.0, time: 2024-08-22 07:28:36 +0000",
        "url": null,
        "grade": "10",
        "score": "10.0",
        "submitted_at": "2024-08-22T07:28:36Z",
        "assignment_id": "14",
        "user_id": "1",
        "submission_type": "online_quiz",
        "workflow_state": "graded",
        "grade_matches_current_submission": "true",
        "graded_at": "2024-08-22T07:28:36Z",
        "grader_id": "-11",
        "attempt": "1",
        "cached_due_date": null,
        "excused": null,
        "late_policy_status": null,
        "points_deducted": null,
        "grading_period_id": null,
        "extra_attempts": null,
        "posted_at": "2024-08-22T07:28:36Z",
        "redo_request": "false",
        "custom_grade_status_id": null,
        "sticker": null,
        "late": "false",
        "missing": "false",
        "seconds_late": "0",
        "entered_grade": "10",
        "entered_score": "10.0",
        "preview_url": "https://170.64.229.73/courses/49/assignments/14/submissions/1?preview=1&version=1",
        "grader": "Graded on submission",
        "assignment_name": "CS Mod 1 Quiz",
        "user_name": "John Smith",
        "current_grade": "10",
        "current_graded_at": "2024-08-22T07:28:36Z",
        "current_grader": "Graded on submission"
    }
]
