#%RAML 1.0
title: hello Local API
version: v1
baseUri: http://localhost:8081/api
mediaType: application/json

/hello:
  get:
    description: Retrieve a mock response
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "Welcome to Mule Rate Limit API!"
              }