[
    {
        "id": 6,
        "description": "",
        "due_at": null,
        "unlock_at": null,
        "lock_at": null,
        "points_possible": 100.0,
        "grading_type": "points",
        "assignment_group_id": 48,
        "grading_standard_id": null,
        "created_at": "2024-08-14T13:43:33Z",
        "updated_at": "2024-08-23T16:57:25Z",
        "peer_reviews": false,
        "automatic_peer_reviews": false,
        "position": 1,
        "grade_group_students_individually": false,
        "anonymous_peer_reviews": false,
        "group_category_id": null,
        "post_to_sis": false,
        "moderated_grading": false,
        "omit_from_final_grade": false,
        "intra_group_peer_reviews": false,
        "anonymous_instructor_annotations": false,
        "anonymous_grading": false,
        "graders_anonymous_to_graders": false,
        "grader_count": 0,
        "grader_comments_visible_to_graders": true,
        "final_grader_id": null,
        "grader_names_visible_to_final_grader": true,
        "allowed_attempts": -1,
        "annotatable_attachment_id": null,
        "hide_in_gradebook": false,
        "secure_params": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjI5MDYwYmJmLWExMmYtNGY4ZS1iZThhLTVlYzdjYTNjMWJiNiJ9.tlpYAzI0Q3seBODuAE2QgHHJGaVsRWXI7ye6AKeqn4Q",
        "lti_context_id": "29060bbf-a12f-4f8e-be8a-5ec7ca3c1bb6",
        "course_id": 48,
        "name": "Create SQL Database",
        "submission_types": [
            "online_text_entry",
            "online_url",
            "online_upload"
        ],
        "has_submitted_submissions": true,
        "due_date_required": false,
        "max_name_length": 255,
        "in_closed_grading_period": false,
        "graded_submissions_exist": true,
        "is_quiz_assignment": false,
        "can_duplicate": true,
        "original_course_id": null,
        "original_assignment_id": null,
        "original_lti_resource_link_id": null,
        "original_assignment_name": null,
        "original_quiz_id": null,
        "workflow_state": "published",
        "important_dates": false,
        "muted": true,
        "html_url": "https://170.64.229.73/courses/48/assignments/6",
        "has_overrides": false,
        "needs_grading_count": 0,
        "sis_assignment_id": null,
        "integration_id": null,
        "integration_data": {},
        "published": true,
        "unpublishable": false,
        "only_visible_to_overrides": false,
        "visible_to_everyone": true,
        "locked_for_user": false,
        "submissions_download_url": "https://170.64.229.73/courses/48/assignments/6/submissions?zip=1",
        "post_manually": false,
        "anonymize_students": false,
        "require_lockdown_browser": false,
        "restrict_quantitative_data": false
    },
    {
        "id": 8,
        "description": "",
        "due_at": null,
        "unlock_at": null,
        "lock_at": null,
        "points_possible": 5.0,
        "grading_type": "points",
        "assignment_group_id": 48,
        "grading_standard_id": null,
        "created_at": "2024-08-19T09:03:10Z",
        "updated_at": "2024-08-21T06:26:39Z",
        "peer_reviews": false,
        "automatic_peer_reviews": false,
        "position": 3,
        "grade_group_students_individually": false,
        "anonymous_peer_reviews": false,
        "group_category_id": null,
        "post_to_sis": false,
        "moderated_grading": false,
        "omit_from_final_grade": false,
        "intra_group_peer_reviews": false,
        "anonymous_instructor_annotations": false,
        "anonymous_grading": false,
        "graders_anonymous_to_graders": false,
        "grader_count": 0,
        "grader_comments_visible_to_graders": true,
        "final_grader_id": null,
        "grader_names_visible_to_final_grader": true,
        "allowed_attempts": -1,
        "annotatable_attachment_id": null,
        "hide_in_gradebook": false,
        "secure_params": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjUzNWUyZDdlLTNhMzUtNDQyNS05MTljLTliNTVlYzMxNTI0NiJ9.653_dzjKbUcrqwWUNa7YCkn-ZE7XeO9WB9idWvD1AOI",
        "lti_context_id": "535e2d7e-3a35-4425-919c-9b55ec315246",
        "course_id": 48,
        "name": "Database Fundamentals Quiz",
        "submission_types": [
            "online_quiz"
        ],
        "has_submitted_submissions": true,
        "due_date_required": false,
        "max_name_length": 255,
        "in_closed_grading_period": false,
        "graded_submissions_exist": true,
        "is_quiz_assignment": true,
        "can_duplicate": false,
        "original_course_id": null,
        "original_assignment_id": null,
        "original_lti_resource_link_id": null,
        "original_assignment_name": null,
        "original_quiz_id": null,
        "workflow_state": "published",
        "important_dates": false,
        "muted": true,
        "html_url": "https://170.64.229.73/courses/48/assignments/8",
        "has_overrides": false,
        "needs_grading_count": 0,
        "sis_assignment_id": null,
        "integration_id": null,
        "integration_data": {},
        "quiz_id": 2,
        "anonymous_submissions": false,
        "published": true,
        "unpublishable": false,
        "only_visible_to_overrides": false,
        "visible_to_everyone": true,
        "locked_for_user": false,
        "submissions_download_url": "https://170.64.229.73/courses/48/quizzes/2/submissions?zip=1",
        "post_manually": false,
        "anonymize_students": false,
        "require_lockdown_browser": false,
        "restrict_quantitative_data": false
    }
]